Repository Tripeer-contest/backend, pull requests merged in 2024-08, with the labels that each got.

#7 feature : admin 더미 사용자 접근방법추가
  tripeer/src/main/java/com/j10d207/tripeer/admin/controller/AdminController.java
  tripeer/src/main/java/com/j10d207/tripeer/admin/dto/req/AdminLoginReq.java
  tripeer/src/main/java/com/j10d207/tripeer/admin/service/AdminService.java
  tripeer/src/main/java/com/j10d207/tripeer/admin/service/AdminServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/common/SecurityConfig.java
  tripeer/src/main/java/com/j10d207/tripeer/common/WebConfig.java
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/user/config/JWTFilter.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/repository/UserRepository.java
  tripeer/src/main/resources/application.yml
Labels: feature

#9 fix : admin login refresh 쿠키에서 헤더로 변경
  tripeer/src/main/java/com/j10d207/tripeer/admin/service/AdminServiceImpl.java
Labels: fix

#11 fix : access 토큰 cookie 전달로 변경
  tripeer/src/main/java/com/j10d207/tripeer/admin/service/AdminServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/config/CustomSuccessHandler.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
  tripeer/src/main/resources/application.yml
Labels: fix

#12 feature : 내 찜목록 조회추가, 마이페이지 찜 추가/삭제 기능추가
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/ContentTypeEnum.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/controller/UserController.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/entity/WishListEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/res/UserDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserService.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: feature

#13 fix : 카카오, 구글 소셜로그인 경로 수정
  tripeer/src/main/resources/application.yml
Labels: fix

#15 feature : 리뷰작성 + 찜목록 평점 노출 추가
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/ReviewDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotReviewEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotReviewRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/vo/ReviewVO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/controller/UserController.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/req/WishlistReq.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/res/UserDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserService.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: feature

#16 fix : 찜목록 추가 에러, 별점없는 상황 대응 추가
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotReviewRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/user/controller/UserController.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/req/WishlistReq.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: fix

#17 fix : 내정보 수정 valid 조건 더 명확하게 수정, 찜목록 추가 예외상황 throw 추가
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/user/controller/UserController.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/req/InfoReq.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: fix

#8 refactor : 정적 팩토리 메소드 화, stream 사용 , dto 분리, valid 추가, service메소드 간소화
  tripeer/src/main/java/com/j10d207/tripeer/email/db/dto/EmailDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/dto/PlanDetailResDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/dto/PublicRootDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/dto/TownDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanBucketEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanDayEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanDetailEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanTownEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/vo/PlanCreateInfoVO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/vo/PlanDetailVO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/CoworkerInvitedReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlaceListReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlanCreateInfoReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlanDetailReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/TitleChangeReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/PlanDetailMainDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/RootOptimizeDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/SpotSearchResDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/ApiRequestServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/config/JWTUtil.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/entity/CoworkerEntity.java
Labels: refactor

#18 feature : place 장소검색 장소 전체 검색, 타입 전체 검색 추가 URL 개편
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/ContentTypeEnum.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotInfoRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
Labels: feature

#19 feat : 플랜 생성시 node 서버에 http요청 보내는 로직 추가
  tripeer/build.gradle
  tripeer/src/main/java/com/j10d207/tripeer/common/WebClientConfig.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/PlanNodeTempleDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: feature

#20 fix : node 탬플릿에 citytown 리스트 값 이상 해결
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/CityEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/dto/TownDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanTownEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/PlanNodeTempleDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#21 feature : 장소 디테일 메인 페이지 로딩 기능 추가
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/ReviewDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotDetailPageDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotReviewRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
Labels: feature

#22 feature : 블로그 검색 정보 추가 반영
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/kakao/db/entity/BlogInfoResponse.java
  tripeer/src/main/java/com/j10d207/tripeer/kakao/service/KakaoService.java
  tripeer/src/main/java/com/j10d207/tripeer/kakao/service/KakaoServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotDetailPageDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotReviewRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/res/UserDTO.java
  tripeer/src/main/resources/application.yml
Labels: feature

#23 feature : runtime에러 커스텀
  tripeer/src/main/java/com/j10d207/tripeer/exception/CustomExceptionHandler.java
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorResponseEntity.java
Labels: feature
