Repository Tripeer-contest/backend, pull requests merged in 2024-09, with the labels that each got.

#24 feat : 초대시 ydoc탬플릿 업데이트
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/NodeInviteDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: feature

#26 feature : 이미지 변수 List화, 리뷰 갯수, 추가정보 첨부 추가
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/ReviewDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotDetailPageDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/AdditionalInfo.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/CultureFacility.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/Festival.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/Food.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/Leports.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/Lodging.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/Shopping.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/TourCourse.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/additional/Tourism.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/CityEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotInfoEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotReviewEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalCultureFacilityEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalFestivalEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalFoodEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalLeportsEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalLodgingEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalShoppingEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalTourCourseEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalTourismEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalCultureFacilityRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalFestivalRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalFoodRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalLeportsRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalLodgingRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalShoppingRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalTourCourseRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/addional/AdditionalTourismRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/AdditionalRepositories.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
Labels: feature

#27 fix : festival entity 변수명 매핑 오류 수정
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalFestivalEntity.java
Labels: fix

#28 fix : 블로그 검색 한글깨짐 오류, 이미지 리스트 공백 제거
  tripeer/src/main/java/com/j10d207/tripeer/kakao/service/KakaoServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotInfoEntity.java
Labels: fix

#29 fix : plan 사용하지 않는 컬럼 삭제
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanDayEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlanCreateInfoReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/PlanDetailMainDTO.java
Labels: refactor, fix

#31 feat : 홈 추천, 키워드 추천 리스트 api 개발
  tripeer/build.gradle
  tripeer/src/main/java/com/j10d207/tripeer/common/WebClientConfig.java
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/RecommendDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotInfoDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/vo/RecommendVO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendServiceImpl.java
  tripeer/src/main/resources/application.yml
Labels: feature

#32 feat : 상세페이지 가까운, 비슷한 관광지 추가
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotDetailPageDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotCollectionEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotCollectionRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
  tripeer/src/main/resources/application.yml
Labels: feature

#34 fix : history null point 해결 plan 생성시 isSaved = false
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanEntity.java
Labels: fix

#30 refactor : stream API화, vaild 도입, 정적 팩토리 메소드 사용
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/ContentTypeEnum.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/CityAndTownDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/CityListDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotAddResDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotDetailDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotInfoDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/SpotListDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/dto/TownListDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotDetailEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotInfoEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotReviewEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/TownEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalBaseEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalCultureFacilityEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalFestivalEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalFoodEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalLeportsEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalLodgingEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalShoppingEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalTourCourseEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/additional/AdditionalTourismEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/vo/ReviewVO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/vo/SpotAddVO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/req/RecommendReq.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/req/ReviewReq.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/req/SpotAddReq.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/AdditionalDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/RecommendDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/ReviewDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/SpotDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/SpotDetailPageDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/CityService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/CityServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/TownService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/TownServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlaceListReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/RootOptimizeDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/CoordinateDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/PublicRootDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/RootInfoDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/ApiRequestService.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/ApiRequestServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/FindRoot.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapService.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapServiceImpl.java
Labels: refactor, feature

#35 feat : 지도 줌기반 검색 구현
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotInfoRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/repository/PlanBucketRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/repository/WishListRepository.java
Labels: feature

#36 fix : 정보수정 이메일 제거, 유저 초대 수락식 변경'
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/entity/CoworkerEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/entity/UserEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/req/InfoReq.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: fix

#37 refactor : 동행자 초대 수락식 변경, 초대된 리스트 조회 추가
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/PlanMemberDto.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/entity/CoworkerEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/repository/CoworkerRepository.java
Labels: feature

#38 fix : 초대 예외상황처리, 각종 조회 시 role을 고려하도록 수정
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/repository/CoworkerRepository.java
Labels: fix

#40 fix : 플랜생성시 타운정보 null 인 문제 해결
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/dto/TownDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#41 fix : 프로필 이미지 삭제경로 못가져오는 오류 수정
  tripeer/src/main/java/com/j10d207/tripeer/s3/service/S3ServiceImpl.java
Labels: fix

#42 feat : 플랜 추천, spotDTO에 평균별점 추가
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotInfoEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/RecommendDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/RecommendSearchDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/SpotDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/SpotSearchResDTO.java
Labels: feature

#43 fix : townDTO 의 title에 city + town 네임으로 변경
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/dto/TownDTO.java
Labels: fix

#44 fix : 에러 수정
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/dto/TownDTO.java
Labels: fix

#45 refactor : 플랜 장소검색 재작성
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotInfoRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: refactor

#46 fix : 마지막페이지 true/false
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/RecommendSearchDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/RecommendServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/SpotSearchResDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#47 fix : 공지사항 목록에 요소 추가
  tripeer/src/main/java/com/j10d207/tripeer/board/dto/res/NoticeRes.java
  tripeer/src/main/java/com/j10d207/tripeer/board/service/BoardNoticeServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlanCreateInfoReq.java
Labels: fix

#48 fix : 관심사 code 같이 가도록 수정
  tripeer/src/main/java/com/j10d207/tripeer/board/service/BoardNoticeServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/TripStyleEnum.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/res/UserDTO.java
Labels: fix

#49 fix : 정보수정 관심사 적은경우 고려
  tripeer/src/main/java/com/j10d207/tripeer/user/db/entity/UserEntity.java
Labels: fix

#50 fix : ContentType 표기 Major로 변경
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/SpotSearchResDTO.java
Labels: fix

#51 fix : 줌레벨 검색 dto 수정
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#52 fix : 검색결과 0 일때 NULL에러 제거
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#53 fix : optimizing rootReq 임시제거
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
Labels: fix

#54 feature : tmap domain refactoring 그리고 반환 방식 개편
  tripeer/src/main/java/com/j10d207/tripeer/common/CommonMethod.java
  tripeer/src/main/java/com/j10d207/tripeer/kakao/service/KakaoService.java
  tripeer/src/main/java/com/j10d207/tripeer/kakao/service/KakaoServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/TimeEnum.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlaceListReq.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/AtoBRes.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/OptimizingRes.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/RootOptimizeDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/RootRes.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/TmapErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/CoordinateDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/PublicRootDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/RootInfoDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/RouteReqDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/ApiRequestService.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/ApiRequestServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapService.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapServiceImpl.java
Labels: refactor, feature

#55 fix : kakao optmizing option hotfix
  tripeer/src/main/java/com/j10d207/tripeer/kakao/service/KakaoServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
Labels: fix

#56 feature : 신규 장소 추가 기능 API
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotInfoEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotInfoRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/req/SpotAddReq.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/SpotDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
Labels: feature

#57 feat: 알림 도메인 구현
  README.md
  tripeer/build.gradle
  tripeer/src/main/java/com/j10d207/tripeer/TripeerApplication.java
  tripeer/src/main/java/com/j10d207/tripeer/common/SecurityConfig.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/FirebaseToken.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/Notification.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/firebase/FirebasePublisher.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/firebase/MessageBody.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/firebase/MessageBuilder.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/firebase/MessageType.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/FirebaseTokenRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/NotificationRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/listener/NotificationEventListener.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/FirebaseTokenService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventHandler.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventTestPublisher.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/TestNotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/util/FCMInitializer.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/util/FirebaseJsonProvider.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/event/CompletePlanEvent.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/event/CoworkerDto.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/event/InviteCoworkerEvent.java
  tripeer/src/main/resources/application.yml
Labels: feature

#58 fix: firebase admin sdk 버전업
  tripeer/build.gradle
Labels: fix

#61 fix : 알림 설정 변경 api 메세지 변경
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: fix

#62 feat : 알림을 위한 각 상황에 대한 적절한 이벤트 생성
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: feature

#63 feat: 알림 읽음처리 API 구현
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/Notification.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationService.java
Labels: feature

#64 feature : 리뷰 이미지 작성 추가
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotReviewEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/req/ReviewReq.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/s3/dto/FileInfoDto.java
  tripeer/src/main/java/com/j10d207/tripeer/s3/dto/S3Option.java
  tripeer/src/main/java/com/j10d207/tripeer/s3/service/S3ServiceImpl.java
Labels: feature

#65 feat : 저장로직 리팩토링 및 저장 스캐쥴러 설정
  tripeer/src/main/java/com/j10d207/tripeer/history/controller/HistoryController.java
  tripeer/src/main/java/com/j10d207/tripeer/history/controller/HistoryControllerDocs.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/req/PlanDetailSaveReq.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/req/PlanSaveReq.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/RouteRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryService.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotInfoEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanDayEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanDetailEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/repository/PlanRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/PlanDetailMainDTO.java
Labels: feature

#66 fix : 항해 항공 순서 변경
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/TmapErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapServiceImpl.java
Labels: fix

#67 fix : 파일 없을경우 버그 수정
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewServiceImpl.java
Labels: fix

#68 각 옵션 최적화, 오류 검증 로직 추가
  tripeer/src/main/java/com/j10d207/tripeer/kakao/service/KakaoServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/TmapErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/entity/PublicRootEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/repository/PublicRootRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/ApiRequestService.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/ApiRequestServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapService.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapServiceImpl.java
Labels: fix

#69 fix : 홈화면 검색 dto에 contentType 추가
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/SpotDTO.java
Labels: fix

#70 feat: 목록조회 API 구현 & notification 및 notification_task 관심사 분리
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/Notification.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/NotificationTask.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/FirebaseTokenRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/NotificationRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/NotificationTaskRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/dto/res/NotificationDto.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/dto/res/NotificationList.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/FirebaseTokenService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventHandler.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationTaskService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/TestNotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/event/InviteCoworkerEvent.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: refactor, feature

#71 fix: allowNotification 에 따른 푸시알림 조건분기 추가
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventHandler.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationTaskService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/TestNotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserService.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: fix

#72 fix : 히스토리 디테일 dto 에 평균 별점과 내가 리뷰작성했는지 추가
  tripeer/src/main/java/com/j10d207/tripeer/history/controller/HistoryController.java
  tripeer/src/main/java/com/j10d207/tripeer/history/controller/HistoryControllerDocs.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistoryDayRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistoryDetailRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistorySpotRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryService.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanDayEntity.java
Labels: fix

#73 fix : 플랜 조회 Role 오류 수정
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/repository/CoworkerRepository.java
Labels: fix

#74 fix: invite 이벤트 dto 에 planTitle null 이슈 해결
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#75 fix: 초대 알림 및 여행 시작 알림 메세지 내용 변경
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/firebase/MessageBuilder.java
Labels: refactor

#76 fix : 초대 수락 조건 변경
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#77 fix: 초대 보낸사람 nickname이 title에 노출되도록 변경
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventHandler.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/event/InviteCoworkerEvent.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#78 fix : 별점 평균 로직 변경, 히스토리 디테일 조회 로직 수정
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistoryDayRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistoryDetailRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistorySpotRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/entity/SpotInfoEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotReviewRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/SpotDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/place/dto/res/SpotDetailPageDto.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewService.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/ReviewServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanDetailEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/repository/PlanRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/SpotSearchResDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/user/dto/res/UserDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/user/service/UserServiceImpl.java
Labels: fix, feature

#79 코드 가독성 정리
  tripeer/src/main/java/com/j10d207/tripeer/plan/controller/PlanController.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/AtoBRes.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/res/OptimizingRes.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanService.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/CoordinateDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapService.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapServiceImpl.java
Labels: refactor

#80 fix : 히스토리 디테일 dto에 spotReviewId 추가
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistoryDayRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistoryDetailRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistorySpotRes.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/place/controller/PlaceController.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotReviewRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/repository/PlanRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/user/db/repository/CoworkerRepository.java
Labels: fix

#81 fix : 히스토리 디테일 핫픽스
  tripeer/src/main/java/com/j10d207/tripeer/history/dto/res/HistoryDayRes.java
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/SpotReviewRepository.java
Labels: fix

#82 fix : 히스토리 한 사람이 한 스팟에 여러개의 리뷰작성가능으로 인한 에러 수정
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryServiceImpl.java
Labels: fix

#83 fix : plan 오늘날짜 시작 가능하게 수정
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlanCreateInfoReq.java
Labels: fix

#84 fix : plan 오늘날짜 시작 가능하게 수정
  tripeer/src/main/java/com/j10d207/tripeer/plan/dto/req/PlanCreateInfoReq.java
Labels: fix

#85 fix : 히스토리 디테일 day, step 에 order by 추가
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/repository/PlanRepository.java
Labels: fix

#86 fix : plan엔티티의 planDayList에 orderby 추가
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/entity/PlanEntity.java
Labels: fix

#87 fix: 알림 버그 수정
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/FirebaseTokenRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/NotificationRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/listener/NotificationEventListener.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/FirebaseTokenService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventTestPublisher.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationTaskService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/TestNotificationService.java
Labels: fix

#88 feat : 히스토리 테스트 코드 추가
  tripeer/src/main/java/com/j10d207/tripeer/history/controller/HistoryController.java
  tripeer/src/main/java/com/j10d207/tripeer/history/controller/HistoryControllerDocs.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryService.java
  tripeer/src/main/java/com/j10d207/tripeer/history/service/HistoryServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix, feature

#89 fix : 가까운 거리 오류에서 1분처리로 변경
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/repository/FirebaseTokenRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/db/TimeEnum.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/PublicRootDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/RootInfoDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/service/TMapServiceImpl.java
Labels: fix

#90 fix : 근처 도보 세부 경로 추가
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/PublicRootDTO.java
  tripeer/src/main/java/com/j10d207/tripeer/tmap/db/dto/RootInfoDTO.java
Labels: fix

#92 feature: 문의사항 작성
  tripeer/src/main/java/com/j10d207/tripeer/board/controller/HelpdeskController.java
  tripeer/src/main/java/com/j10d207/tripeer/board/db/entity/BoardHelpdeskEntity.java
  tripeer/src/main/java/com/j10d207/tripeer/board/db/repository/BoardHelpdeskRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/board/dto/res/HelpdeskRes.java
  tripeer/src/main/java/com/j10d207/tripeer/board/service/BoardHelpdeskService.java
  tripeer/src/main/java/com/j10d207/tripeer/board/service/BoardHelpdeskServiceImpl.java
  tripeer/src/main/java/com/j10d207/tripeer/common/CommonMethod.java
  tripeer/src/main/java/com/j10d207/tripeer/common/SecurityConfig.java
Labels: feature

#93 fix : 관광지 디테일 조회에서 관광지 추가로 인한 비슷한 관광지, 가까운 관광지가 없어 이를 처리
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
Labels: fix

#94 fix :관광지 디테일 조회에서 비슷한, 가까운 관광지 null이 아닌 빈 리스트로 변경
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
Labels: fix

#95 fix : 관광지 디테일에서 프론트가 사용하지 않는 overview 삭제
  tripeer/src/main/java/com/j10d207/tripeer/place/service/SpotServiceImpl.java
Labels: fix

#96 refactor: data layer와 비즈니스 로직에서 사용하는 객체 분리
  tripeer/src/main/java/com/j10d207/tripeer/exception/ErrorCode.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/FirebaseToken.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/NotificationTask.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/firebase/MessageBuilder.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/dto/NotificationDto.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/dto/NotificationMap.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/dto/Token.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/dto/TokenMap.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/mapper/FirebaseTokenMapper.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/mapper/NotificationMapper.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/mapper/NotificationTaskMapper.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/FirebaseTokenService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventHandler.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationEventTestPublisher.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/NotificationTaskService.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/TestNotificationService.java
Labels: refactor

#97 fix: flutter app 의 경우 Notification 객체를 전달하도록 변경
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/FirebaseToken.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/NotificationTask.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/firebase/MessageBuilder.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/dto/Token.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/mapper/FirebaseTokenMapper.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/FirebaseTokenService.java
Labels: fix

#98 fix: token 저장 enum String 전략 추가
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/db/entity/FirebaseToken.java
  tripeer/src/main/java/com/j10d207/tripeer/noti/service/TestNotificationService.java
Labels: fix

#99 fix: 토큰추가 API logging 추가
  tripeer/src/main/java/com/j10d207/tripeer/noti/controller/NotificationController.java
Labels: fix

#100 fix : 위시리스트 TDO 에 담긴 정보 수정
  tripeer/src/main/java/com/j10d207/tripeer/place/db/repository/ElasticSpotRepository.java
  tripeer/src/main/java/com/j10d207/tripeer/plan/service/PlanServiceImpl.java
Labels: fix

#101 fix : weather(기상청) api키 '양건우'것으로 변경
  tripeer/src/main/resources/application.yml
Labels: fix

#102 fix : 날씨 현재 시간 날씨만 조회로 변경
  tripeer/src/main/java/com/j10d207/tripeer/weather/controller/WeatherController.java
  tripeer/src/main/java/com/j10d207/tripeer/weather/service/WeatherService.java
  tripeer/src/main/java/com/j10d207/tripeer/weather/service/WeatherServiceImpl.java
Labels: fix

#103 fix : 도커 파일에 타임존 설정하는 코드 추가
  tripeer/Dockerfile
Labels: fix

#104 fix : 도커파일 ubuntu가 아닌 alpine에 맞게 변경
  tripeer/Dockerfile
Labels: fix

#105 fix : 타임존을 os가 아닌 스프링에 설정하도록 변경
  tripeer/Dockerfile
Labels: fix

#106 fix : 네이버 로그인 정상화
  tripeer/src/main/resources/application.yml
Labels: fix
